---
title: "GLM model peptidomics data DCS"
author: "R.C.Slieker & G.A.Bouland"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: md_document
---

## Load packages

```{r setup, message=FALSE, eval=FALSE}
library(datashieldclient)
library(dsBaseClient)
library(dsSwissKnifeClient)
library(survminer)
library(survival)
library(reshape2)
library(viridis)

#setwd("D:/001_Projects/001_RHAPSODY/")
knitr::opts_knit$set(root.dir = "D:/001_Projects/001_RHAPSODY/")
```

## Login

```{r login, message=F, eval=FALSE}
source("D:/001_Projects/001_RHAPSODY/001.Scripts/001 New utils/Utils_CoxModels.R")
source("D:/001_Projects/001_RHAPSODY/001.Scripts/001 New utils/Utils_GB.R")
source("D:/001_Projects/001_RHAPSODY/001.Scripts/001 New utils/Utils.R")

datasource <- "opal"
loginpath <- "logindata_template.txt"
cohort <- "dcs"

logins <- read.table(loginpath, header=T)
logins <- logins[logins$server %in% c(cohort),]
assign("opal",datashield.login(logins), envir = .GlobalEnv)
```
 
## Load data

```{r load, eval=FALSE}
#Select required attributes 
myAttributes <- c("SOMALOGIC","CLUSTER","SEX","AGE","BMI","HBA1C","HDL","LDL","TRIG","CPEPTIDE","TimeToSpin")
myTransform <-c(3,rep(0, length(myAttributes)-1))
prepareData(assign="ModelData",opal=opal,attributes=myAttributes,cohort = "dcs",
            transformVector=myTransform)
```

# Run models 

```{r linreg, message=FALSE, eval=FALSE}
peptides <- ds.colnames('ModelData')$dcs
peptides <- peptides[grep("SL0", peptides)]

# SIDD comparisons
DCS.pept.SIDD.adj  <- getModelForClusters(peptides, compCluster=2, refCluster="3,4,5,6", formula='ModelData.subset$%s~ModelData.subset$newCluster + ModelData.subset$LBTESTCD.TimeToSpin+ ModelData.subset$LBTESTCD.HBA1C')

DCS.pept.SIRD.adj  <- getModelForClusters(peptides, compCluster=3, refCluster="2,4,5,6", formula='ModelData.subset$%s~ModelData.subset$newCluster + ModelData.subset$LBTESTCD.TimeToSpin+ ModelData.subset$LBTESTCD.CPEPTIDE')

DCS.pept.MOD.adj  <- getModelForClusters(peptides, compCluster=4, refCluster="2,3,5,6", formula='ModelData.subset$%s~ModelData.subset$newCluster + ModelData.subset$LBTESTCD.TimeToSpin + ModelData.subset$VSTESTCD.BMI')

DCS.pept.MDH.adj   <- getModelForClusters(peptides, compCluster=6, refCluster="2,3,4,5", formula='ModelData.subset$%s~ModelData.subset$newCluster + ModelData.subset$LBTESTCD.TimeToSpin + ModelData.subset$LBTESTCD.HDL')

DCS.pept.MDH.adj_TRIG   <- getModelForClusters(peptides, compCluster=6, refCluster="2,3,4,5", formula='ModelData.subset$%s~ModelData.subset$newCluster + ModelData.subset$LBTESTCD.TimeToSpin + ModelData.subset$LBTESTCD.HDL + ModelData.subset$LBTESTCD.TRIG')

save(DCS.pept.SIDD.adj, 
     DCS.pept.SIRD.adj, 
     DCS.pept.MOD.adj, 
     DCS.pept.MDH.adj, 
     DCS.pept.MDH.adj_TRIG, 
     file="./000.Final_Scripts/002.Clusters.Data/Peptides GLM_models across clusters_FDB_DCS_OneVsAll_adjusted.RData")
```

```{r, eval=FALSE, echo=FALSE}
load("./000.Final_Scripts/002.Clusters.Data/Peptides GLM_models across clusters_FDB_DCS_OneVsAll.RData")
```

## Quick check, how many significant?

### SIDD

```{r, eval=FALSE}
DCS.peptidomics.results.SIDD[DCS.peptidomics.results.SIDD$p.adj <= 0.05,]
table(DCS.peptidomics.results.SIDD$p.adj <= 0.05)
```

### SIRD 

```{r, eval=FALSE}
DCS.peptidomics.results.SIRD[DCS.peptidomics.results.SIRD$p.adj <= 0.05,]
table(DCS.peptidomics.results.SIRD$p.adj <= 0.05)
```

### MOD

```{r, eval=FALSE}
DCS.peptidomics.results.MOD[DCS.peptidomics.results.MOD$p.adj <= 0.05,]
table(DCS.peptidomics.results.MOD$p.adj <= 0.05)
```

### MARD

```{r, eval=FALSE}
DCS.peptidomics.results.MARD[DCS.peptidomics.results.MARD$p.value <= 0.05,]
table(DCS.peptidomics.results.MARD$p.adj <= 0.05)
```

### MARDH

```{r, eval=FALSE}
DCS.peptidomics.results.MARDH[DCS.peptidomics.results.MARDH$p.value <= 0.05,]
table(DCS.peptidomics.results.MARDH$p.adj <= 0.05)
```

```{r logout, echo=F, eval=FALSE}
datashield.logout(opal)
```