---
title: "GLM model metabolomics andis"
author: "Gerard Bouland / Roderick Slieker"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/roderick/Documents/Projecten en papers/Rhapsody_FDB/")
setwd("/mnt/d/001_Projects/001_RHAPSODY")
#knitr::opts_knit$set(root.dir = "/exports/molepi/users/gbouland/")
```

```{r packs, message=FALSE, eval=TRUE}
library(datashieldclient)
library(dsCDISCclient)
library(survminer)
library(survival)
library(dsModellingClient)
```

```{r login, message=F}
source("./000.Final_Scripts/003.Utils/Utils_GB.R")
source("./000.Final_Scripts/003.Utils/Utils_CoxModels.R")
loginpath <- "logindata_template.txt"
cohort <- "andis"
datasource <- "opal"
logIn(datasource, loginpath, cohort)
```

```{r load}
myAttributes <- c("METABOLOMICS","CLUSTER")
myTransform <-c(3,0)

datashield.assign(opal[1], "lb", "rhapsody.LB")
ds.dim(	"lb", datasources  = opal[1])
ds2.subset(symbol = "lb", what = "lb", row.filter='-which(lb$LBRUNID == "Run2")')
ds.dim(	"lb", datasources  = opal[1])

prepareData(assign="ModelData",opal=opal,attributes=myAttributes,transformVector=myTransform)
```

# Run models

```{r linreg, message=FALSE, results='hide'}
metabolites <- ds.colnames('ModelData')$andis
metabolites <- metabolites[which(metabolites == "LBTESTCD.AADA"):which(metabolites == "LBTESTCD.Tyr")]

# SIDD comparisons
ANDIS.metabolomics.results.SIDD  <- getModelForClusters(metabolites, compCluster=2, refCluster="3,4,5,6")
ANDIS.metabolomics.results.SIRD  <- getModelForClusters(metabolites, compCluster=3, refCluster="2,4,5,6")
ANDIS.metabolomics.results.MOD  <- getModelForClusters(metabolites, compCluster=4, refCluster="2,3,5,6")
ANDIS.metabolomics.results.MARD  <- getModelForClusters(metabolites, compCluster=5, refCluster="2,3,4,6")
ANDIS.metabolomics.results.MARDH  <- getModelForClusters(metabolites, compCluster=6, refCluster="2,3,4,5")

save(ANDIS.metabolomics.results.SIDD, 
     ANDIS.metabolomics.results.SIRD, 
     ANDIS.metabolomics.results.MOD, 
     ANDIS.metabolomics.results.MARD, 
     ANDIS.metabolomics.results.MARDH, 
     file="./000.Final_Scripts/002.Clusters.Data/Metabolites GLM_models across clusters_FDB_ANDIS_OneVsAll.RData")
```

### SIDD

```{r}
ANDIS.metabolomics.results.SIDD[ANDIS.metabolomics.results.SIDD$p.adj <= 0.05,]
table(ANDIS.metabolomics.results.SIDD$p.adj <= 0.05)
```

### SIRD 

```{r}
ANDIS.metabolomics.results.SIRD[ANDIS.metabolomics.results.SIRD$p.adj <= 0.05,]
table(ANDIS.metabolomics.results.SIRD$p.adj <= 0.05)
```

### MOD

```{r}
ANDIS.metabolomics.results.MOD[ANDIS.metabolomics.results.MOD$p.adj <= 0.05,]
table(ANDIS.metabolomics.results.MOD$p.adj <= 0.05)
``` 

### MARD

```{r}
ANDIS.metabolomics.results.MARD[ANDIS.metabolomics.results.MARD$p.value <= 0.05,]
table(ANDIS.metabolomics.results.MARD$p.adj <= 0.05)
```

### MARDH

```{r}
ANDIS.metabolomics.results.MARDH[ANDIS.metabolomics.results.MARDH$p.value <= 0.05,]
table(ANDIS.metabolomics.results.MARDH$p.adj <= 0.05)
```

```{r logout, echo=F}
logOut(datasource)
```
