---
title: "GLM model lipidomics data GoDARTS"
author: "R.C.Slieker"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: md_document
---

## Load packages

```{r setup, message=FALSE, eval=TRUE}
library(datashieldclient)
library(dsCDISCclient)
library(survminer)
library(survival)
library(reshape2)
library(viridis)

knitr::opts_knit$set(root.dir = "D:/001_Projects/001_RHAPSODY/")
```

## Login

Login on the DCS node only for now

```{r login, message=F, eval=FALSE}
source("./000.Final_Scripts/003.Utils/Utils.R")
source("./000.Final_Scripts/003.Utils/Utils_GB.R")

logins <- read.table("logindata_template.txt", header=T)
logins <- logins[logins$server %in% "godarts",]

opal <- datashield.login(logins)
opal
```
 
## Load data

```{r load,eval=FALSE, eval=FALSE}
datashield.assign(opal, 'lb','rhapsody.LB')
datashield.assign(opal, 'vs','rhapsody.VS')
datashield.assign(opal, 'dm','rhapsody.DM')
datashield.assign(opal, 'cm','rhapsody.CM')

#Select required attributes 
myAttributes <- c("LIPIDOMICS","TIMEINSULIN","TIMEINSULINSTATUS","CLUSTER")
#Determine which attributes need to be transformed
#   0 = none
#   1 = log10(x+1)
#   2 = scale(x)
#   3 = scale(log10(x+1))
myTransform <-c(3,0,0,0)

#Prepare dataframe
prepareData(assign="ModelData",opal=opal,attributes=myAttributes,removeNA=FALSE,transformVector=myTransform,cohort="godarts")
```

# Run models 

Using the function `ds.glm` models for the 199 lipids. lipids are `log10` transformed and `scaled`. 

```{r linreg, message=FALSE, eval=FALSE}
lipids <- ds.colnames('ModelData')$godarts
lipids <- lipids[which(lipids == "LBTESTCD.CE.14.0.0"):which(lipids == "LBTESTCD.TAG.58.8.0")]

# SIDD comparisons
GoDARTS.lipidomics.results.SIDD  <- getModelForClusters(lipids, compCluster=2, refCluster="3,4,5,6")
GoDARTS.lipidomics.results.SIRD  <- getModelForClusters(lipids, compCluster=3, refCluster="2,4,5,6")
GoDARTS.lipidomics.results.MOD  <- getModelForClusters(lipids, compCluster=4, refCluster="2,3,5,6")
GoDARTS.lipidomics.results.MARD  <- getModelForClusters(lipids, compCluster=5, refCluster="2,3,4,6")
GoDARTS.lipidomics.results.MARDH  <- getModelForClusters(lipids, compCluster=6, refCluster="2,3,4,5")

save(GoDARTS.lipidomics.results.SIDD, 
     GoDARTS.lipidomics.results.SIRD, 
     GoDARTS.lipidomics.results.MOD, 
     GoDARTS.lipidomics.results.MARD, 
     GoDARTS.lipidomics.results.MARDH, 
     file="./000.Final_Scripts/002.Clusters.Data/Lipids GLM_models across clusters_FDB_GoDARTS_OneVsAll.RData")
```

```{r, eval=TRUE, echo=FALSE}
load("./000.Final_Scripts/002.Clusters.Data/lipids GLM_models across clusters_FDB_DCS_OneVsAll.RData")
```

## Quick check, how many significant?

### SIDD

```{r}
GoDARTS.lipidomics.results.SIDD[GoDARTS.lipidomics.results.SIDD$p.adj <= 0.05,]
table(GoDARTS.lipidomics.results.SIDD$p.adj <= 0.05)
```

### SIRD 

```{r}
GoDARTS.lipidomics.results.SIRD[GoDARTS.lipidomics.results.SIRD$p.adj <= 0.05,]
table(GoDARTS.lipidomics.results.SIRD$p.adj <= 0.05)
```

### MOD

```{r}
GoDARTS.lipidomics.results.MOD[GoDARTS.lipidomics.results.MOD$p.adj <= 0.05,]
table(GoDARTS.lipidomics.results.MOD$p.adj <= 0.05)
```

### MARD

```{r}
GoDARTS.lipidomics.results.MARD[GoDARTS.lipidomics.results.MARD$p.value <= 0.05,]
table(GoDARTS.lipidomics.results.MARD$p.adj <= 0.05)
```

### MARDH

```{r}
GoDARTS.lipidomics.results.MARDH[GoDARTS.lipidomics.results.MARDH$p.value <= 0.05,]
table(GoDARTS.lipidomics.results.MARDH$p.adj <= 0.05)
```

```{r logout, echo=F, eval=FALSE}
datashield.logout(opal)
```