---
title: "Combine cluster analyses for peptidomics"
author: "R.C.Slieker"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: md_document
---

```{r setup, include=FALSE, message=F, eval=F}
library(knitr)
library(survival)
library(reshape2)
library(viridis)
library(ggplot2)
knitr::opts_knit$set(root.dir = "D:/001_Projects/001_RHAPSODY/")
options(stringsAsFactors = F)
```

# Read data

```{r, eval=F}
#COnversion
load("./002.Data/Conversion_Peptides.RData")

#Mean levels
load("./002.Data Combined/Peptide_MeanSD_data.RData")


# Load data
load("002.Data/DCS.Results.SIDD.RData")
load("002.Data/DCS.Results.SIRD.RData")
load("002.Data/DCS.Results.MOD.RData")
load("002.Data/DCS.Results.MARD.RData")
load("002.Data/DCS.Results.MARDH.RData")

load("002.Data GoDARTS/Somalogic_GoDARTS.Results.SIDD.RData")
load("002.Data GoDARTS/Somalogic_GoDARTS.Results.SIRD.RData")
load("002.Data GoDARTS/Somalogic_GoDARTS.Results.MOD.RData")
load("002.Data GoDARTS/Somalogic_GoDARTS.Results.MARD.RData")
load("002.Data GoDARTS/Somalogic_GoDARTS.Results.MARDH.RData")

peptides <- intersect(results.SIDD.DCS$var, results.SIDD.GoDARTS$var)

updateData <- function(data)
{
  data <- data[match(peptides, data$var),]
  data$p.adj <- p.adjust(data$p.value,'fdr')
  print(table(data$p.adj <= 0.05))
  return(data)
}

#Update DCS
results.SIDD.DCS  <- updateData(results.SIDD.DCS)
results.SIRD.DCS  <- updateData(results.SIRD.DCS)
results.MOD.DCS   <- updateData(results.MOD.DCS)
results.MARD.DCS  <- updateData(results.MARD.DCS)
results.MARDH.DCS <- updateData(results.MARDH.DCS)

#Update GoDARTS
results.SIDD.GoDARTS  <- updateData(results.SIDD.GoDARTS)
results.SIRD.GoDARTS  <- updateData(results.SIRD.GoDARTS)
results.MOD.GoDARTS   <- updateData(results.MOD.GoDARTS)
results.MARD.GoDARTS  <- updateData(results.MARD.GoDARTS)
results.MARDH.GoDARTS <- updateData(results.MARDH.GoDARTS)
```

```{r, eval=F}
get.plot <- function(dataDCS, dataGODARTS, title)
{
  pd <- data.frame(Beta.DCS = dataDCS$Estimate, Beta.GoDARTS = dataGODARTS$Estimate)
  pd$Sign <- ifelse(dataDCS$p.adj <= 0.05 & dataGODARTS$p.adj <= 0.05, "Sign", "NonSign")
  #cov <- conversion[match(dataDCS$var, conversion$SomaId),]
  
  #pd$label <- factor(ifelse(pd$Sign == "Sign", cov$Target, NA))
  
  minx <- round(min(c(pd$Beta.DCS, pd$Beta.GoDARTS)), 1)
  maxx <- round(max(c(pd$Beta.DCS, pd$Beta.GoDARTS)), 1)
  
  
  
  P <- ggplot(pd, aes(x=Beta.DCS, y=Beta.GoDARTS, col=Sign))+
    geom_point()+
    #geom_text()+
    scale_colour_manual(values = c("#A4A4A4","#21908CFF"))+
    xlab("Estimate DCS")+
    ylab("Estimate GoDARTS")+
    ggtitle(title)+
    geom_smooth(method=lm, col='black')+
    geom_vline(xintercept = 0)+
    geom_hline(yintercept = 0)+
    theme(legend.position = 'none')
    #ylim(minx,maxx)+
    #xlim(minx,maxx)
  return(P)
}

p.sidd <- get.plot(results.SIDD.DCS, results.SIDD.GoDARTS, title="SIDD vs all DCS/GoDARTS")
p.sird <- get.plot(results.SIRD.DCS, results.SIRD.GoDARTS, title="SIRD vs all DCS/GoDARTS")
p.mod <- get.plot(results.MOD.DCS, results.MOD.GoDARTS, title="MOD vs all DCS/GoDARTS")
p.mard <- get.plot(results.MARD.DCS, results.MARD.GoDARTS, title="MARD vs all DCS/GoDARTS")
p.mardh <- get.plot(results.MARDH.DCS, results.MARDH.GoDARTS, title="MARDH vs all DCS/GoDARTS")


a1 <- cbind(ggplotGrob(p.sidd),ggplotGrob(p.sird),ggplotGrob(p.mod),
            ggplotGrob(p.mard),ggplotGrob(p.mardh), size="first")

pdf("./003.Figures.combined/Lipidomics comparison of estimates of vsAll.pdf", width=16, height=3)
plot(a1)
dev.off()

```

```{r, eval=F}
library(meta)

getMetaData <- function(group)
{
  data1 <- get(sprintf("results.%s.DCS", group))
  data2 <- get(sprintf("results.%s.GoDARTS", group))
  
  vars <- unique(data1$var)
  
  .getForVar <- function(var.sel)
  {
    #k=1
    var.sel <- as.character(var.sel)
    
    #Subset
    dx <- rbind(data1[match(var.sel, data1$var),],
                data2[match(var.sel, data2$var),])
    
    #Combine
    fit <- metagen(TE = dx$Estimate, seTE = dx$Std..Error, studlab = dx$study, comb.fixed = TRUE, comb.random = TRUE)
    out <- data.frame(var.sel,
                      Effect.fixed = fit$TE.fixed, SE.fixed = fit$seTE.fixed, 
                      Zval.fixed = fit$zval.fixed, Pval.fixed = fit$pval.fixed, 
                      Effect.random = fit$TE.random, SE.random = fit$seTE.random, 
                      Zval.random = fit$zval.random, Pval.random  = fit$pval.random, 
                      I2 = summary(fit)$I2$TE, Het = pchisq(fit$Q,1, lower.tail=F))
    
    
    out
  }
  res.all <- lapply(vars, .getForVar)
  outData <- do.call(rbind, res.all)
  #Sort pval
  outData <- outData[order(outData$Pval.random, decreasing=F),]
  
  #ADj pval
  outData$Pval.random.adj <- p.adjust(outData$Pval.random, 'bonferroni')
  outData.sign <- outData
  #Print
  print(nrow(outData.sign))
  print(table(outData.sign[outData.sign$Pval.random.adj <= 0.05,]$Effect.random >= 0))
  
  #convert
  outData.sign$Target <- conversion[match(outData.sign$var.sel, conversion$SomaId),"Target"]
  
  #Return to disk and envir
  
  outData.sign$p.adj <- outData.sign$Pval.random.adj
  outData.sign$name <- peptideNames[match(outData.sign$var.sel, peptideNames$SomaId),"UniProt"]
  write.table(outData.sign[outData.sign$Pval.random.adj <= 0.05,], file=sprintf('./003.Figures.combined/Peptidomics meta %s.csv', group), sep=",", quote=F, row.names=F)

  return(outData.sign)
  
}


library(meta)
meta.sidd <- getMetaData("SIDD")
meta.sird <- getMetaData("SIRD")
meta.mod <- getMetaData("MOD")
meta.mard <- getMetaData("MARD")
meta.mardh <- getMetaData("MARDH")




save(meta.sidd, meta.sird, meta.mod, meta.mard, meta.mardh, file="./003.Figures.combined/Peptidomics GoDARTS DCS meta analysis_onevsall.RData")
```

```{r, eval=F}
head(mean.PeptideData)
mean.Peptides.M <- melt(mean.PeptideData, id.vars = c("Mean","pep","cluster", "cohort"))
mean.Peptides.M$pep <- gsub("LBTESTCD.","",mean.Peptides.M$pep)
head(mean.Peptides.M)

getPlot <- function(var)
{
  pd <- mean.Peptides.M[mean.Peptides.M$pep %in% var,]
  Target <- rep(conversion[match(var, conversion$SomaId),"Target"])
  head(pd)
  p1 <- ggplot(pd, aes(x=factor(cluster), y=value, fill=factor(cluster)))+
    geom_boxplot()+
    facet_grid(~cohort, scale="free_x")+
    scale_fill_manual(values = viridis::viridis_pal()(5))+
    ggtitle(Target)+
    ylab("Levels")
  
  png(filename = sprintf("./003.Figures.combined/Plot_of_%s_%s.png", var, Target), width=5, height=3, units = "in", res=200)
  plot(p1)
  dev.off()
  
  return(p1)
}

```


```{r, eval=FALSE, echo=TRUE}
source("./001.Scripts/Utils.R")
logins <- read.table("logindata_template.txt", header=T)
logins <- logins[logins$server %in% c("dcs","godarts"),]

opal1 <- datashield.login(logins[logins$server %in% 'dcs',])
opal2 <- datashield.login(logins[logins$server %in% 'godarts',])

prepare.dcs.somalogic(opal = opal1)
prepare.godarts.somalogic(opal = opal2)
```

## Correlation and context specific correlation

```{r, eval=FALSE, echo=TRUE}
object.name <- "ModelData"

getCorrelationCluster <- function(object.name)
{
  # All individuals 
  corr.dcs <- ds.cor(x='ModelData', naAction = "pairwise.complete.obs", datasources = opal1)
  corr.godarts <- ds.cor(x='ModelData', naAction = "pairwise.complete.obs", datasources = opal2)
  res.all <- list(dcs = corr.dcs, godarts = corr.godarts)
  
  #For each cluster seperate
  null.list <- lapply(2:6, FUN = function(x){
    ds2.subset(symbol = paste0("ModelData.C",x), what = "ModelData", row.filter = sprintf("which(ModelData$LBTESTCD.CLUSTER == %s)",x), 
               datasources = opal1)  
    ds2.subset(symbol = paste0("ModelData.C",x), what = "ModelData", row.filter = sprintf("which(ModelData$LBTESTCD.CLUSTER == %s)",x), 
               datasources = opal2)  
  })
  
  #Now correlation for each cluster seperate
  
  C2.dcs = ds.cor(x='ModelData.C2', naAction = "pairwise.complete.obs", datasources = opal1)
  C2.godarts = ds.cor(x='ModelData.C2', naAction = "pairwise.complete.obs", datasources = opal2)

  C3.dcs = ds.cor(x='ModelData.C3', naAction = "pairwise.complete.obs", datasources = opal1)
  C3.godarts = ds.cor(x='ModelData.C3', naAction = "pairwise.complete.obs", datasources = opal2)
  
  C4.dcs = ds.cor(x='ModelData.C4', naAction = "pairwise.complete.obs", datasources = opal1)
  C4.godarts = ds.cor(x='ModelData.C4', naAction = "pairwise.complete.obs", datasources = opal2)
  
  C5.dcs = ds.cor(x='ModelData.C5', naAction = "pairwise.complete.obs", datasources = opal1)
  C5.godarts = ds.cor(x='ModelData.C5', naAction = "pairwise.complete.obs", datasources = opal2)
  
  C6.dcs = ds.cor(x='ModelData.C6', naAction = "pairwise.complete.obs", datasources = opal1)
  C6.godarts = ds.cor(x='ModelData.C6', naAction = "pairwise.complete.obs", datasources = opal2)
  
  
  res <- list(C2.dcs,C2.godarts,C3.dcs,C3.godarts,C4.dcs,C4.godarts,C5.dcs,C5.godarts,C6.dcs,C6.godarts)
  names(res) <- list("C2.dcs","C2.godarts","C3.dcs","C3.godarts","C4.dcs","C4.godarts","C5.dcs","C5.godarts","C6.dcs","C6.godarts")
  
  #Give back
  res <- list(ALL = res.all, CLUSTER = res)
  return(res)
}

correlation.DCS.GoDARTS <- getCorrelationCluster("ModelData")
```

```{r, eval=FALSE, echo=F}
save(correlation.DCS.GoDARTS, file="./002.Data Combined/Correlation_DCS.GoDARTS_PeptidesClinical.RData")
```

```{r, echo=F, eval=FALSE}
load("002.Data Combined/Correlation_DCS.GoDARTS_PeptidesClinical.RData")
var.base <- c("VSTESTCD.BMI","AGE","LBTESTCD.HDL","LBTESTCD.HBA1C","LBTESTCD.CPEPTIDE")
lab.base <- c("BMI","Age","HDL","HbA1C","C-peptide")

getHdata <- function(var.row, var.col)
{
  all.data <- cbind(correlation.DCS.GoDARTS$ALL$dcs$dcs$` --correlation`[var.row,var.col],
        correlation.DCS.GoDARTS$ALL$godarts$godarts$` --correlation`[var.row,var.col])
        
  colnames(all.data) <- paste0(rep(c("BMI","Age","HDL","HbA1c","C-peptide"),2),".all.",rep(c("DCS","GoDARTS"), each=5))

  getForCluster <- function(cluster){
    out <- cbind(
        correlation.DCS.GoDARTS[["CLUSTER"]][[sprintf("C%s.%s",cluster, "dcs")]][["dcs"]]$` --correlation`[var.row,var.col],
        correlation.DCS.GoDARTS[["CLUSTER"]][[sprintf("C%s.%s",cluster, "godarts")]][["godarts"]]$` --correlation`[var.row,var.col])
    
    cols <- rep(c("BMI","Age","HDL","HbA1c","C-peptide"),2)

    colnames(out) <- paste0(cols,".c",cluster,".",rep(c("DCS","GoDARTS"), each=5))
    return(out)
  }
  newdata <- do.call(cbind, lapply(2:6, getForCluster))
        
  
  all.complete.data <- cbind(all.data, newdata)
  all.complete.data <-all.complete.data[,sort(colnames(all.complete.data))]
  cols <- rep(c("Age","BMI","C-peptide","HbA1c","HDL"),each=12)
  neworder <- labels(as.dendrogram(hclust(dist(all.complete.data))))
  newtargets <- conversion[match(rownames(all.complete.data), paste0("LBTESTCD.", conversion$SomaId)),"Target"]
  neworder.targets <- conversion[match(neworder, paste0("LBTESTCD.", conversion$SomaId)),"Target"]
  rownames(all.complete.data) <- newtargets
  acd <- reshape2::melt(all.complete.data)
  acd$Var1 <- factor(as.character(acd$Var1), levels=neworder.targets)
  acd.col <- colsplit(acd$Var2, "\\.", names = LETTERS[1:3])
  acd.c <- data.frame(acd, acd.col)
  p1 <- ggplot(acd.c, aes(x=C, y=Var1, fill=value))+
  geom_tile()+
  facet_grid(~B)+
  scale_fill_gradientn(colours = c("#FF0000", "white", "#0000FF"),values = scales::rescale(c(-1,0,1)),
                       guide="colorbar",limits=c(-1,1))+
  theme_minimal()+
  xlab("Group")+
  ylab("Peptide")
  return(p1)
}



```

## SIDD

```{r, eval=FALSE}
meta.sidd.sign <- meta.sidd[meta.sidd$p.adj <= 0.05,]
table(meta.sidd.sign$Effect.random >= 0)

knitr::kable(meta.sidd.sign[,c(1,6:13)])

#Down
getPlot("SL010501")
getPlot("SL000498")

#Up
getPlot("SL010464")

var.sidd <- paste0("LBTESTCD.",meta.sidd.sign$var.sel)
lab.sidd <- conversion[match(var.sidd, paste0("LBTESTCD.", conversion$SomaId)),"Target"]
all.lab.sidd <- c(lab.base, lab.sidd)
print(getHdata(var.sidd, var.base))
```

## SIRD

```{r, eval=F}
meta.sird.sign <- meta.sird[meta.sird$p.adj <= 0.05,]
table(meta.sird.sign$Effect.random >= 0)
knitr::kable(meta.sird.sign[,c(1,6:13)])

#Down
getPlot("SL000525")
getPlot("SL005156")

getPlot("SL003869")
#Up
getPlot("SL009328")
getPlot("SL004747")


var.sird <- paste0("LBTESTCD.",meta.sird.sign$var.sel)
lab.sird <- conversion[match(var.sird, paste0("LBTESTCD.", conversion$SomaId)),"Target"]


print(getHdata(var.sird, var.base))
```

## MOD

```{r, eval=F}
meta.mod.sign <- meta.mod[meta.mod$p.adj <= 0.05,]
table(meta.mod.sign$Effect.random >= 0)
knitr::kable(meta.mod.sign[,c(1,6:13)])

#Down
getPlot("SL005231")
getPlot("SL001997")

#Up
getPlot("SL007151")

var.mod <- paste0("LBTESTCD.",meta.mod.sign$var.sel)
lab.mod <- conversion[match(var.mod, paste0("LBTESTCD.", conversion$SomaId)),"Target"]

print(getHdata(var.mod, var.base))
```

## MARD

```{r, eval=F}
meta.mard.sign <- meta.mard[meta.mard$p.adj <= 0.05,]
table(meta.mard.sign$Effect.random >= 0)
knitr::kable(meta.mard.sign[,c(1,6:13)])

getPlot("SL001774")
getPlot("SL005789")
getPlot("SL000498")


var.mard <- paste0("LBTESTCD.",meta.mard.sign$var.sel)
lab.mard <- conversion[match(var.mard, paste0("LBTESTCD.", conversion$SomaId)),"Target"]

print(getHdata(var.mard, var.base))
```


## MDH

```{r, eval=F}
meta.mardh.sign <- meta.mardh[meta.mardh$p.adj <= 0.05,]
table(meta.mardh.sign$Effect.random >= 0)
knitr::kable(meta.mardh.sign[,c(1,6:13)])

getPlot("SL004639")
getPlot("SL002704")
getPlot("SL010378")

var.mardh <- paste0("LBTESTCD.",meta.mardh.sign$var.sel)
lab.mardh <- conversion[match(var.mardh, paste0("LBTESTCD.", conversion$SomaId)),"Target"]

print(getHdata(var.mardh, var.base))
```

## Get heatmap of meta-estimates.

```{r, eval=F}
vars <- unique(c(meta.sidd.sign$var.sel, meta.sird.sign$var.sel, meta.mod.sign$var.sel,
  meta.mard.sign$var.sel, meta.mardh.sign$var.sel))

#Make sign matrix
sign.matrix <- matrix(rep(0), ncol=5, nrow=length(vars))
colnames(sign.matrix) <- c("SIDD","SIRD","MOD","MARD","MARDH")
rownames(sign.matrix) <- vars

#
sign.matrix[match(meta.sidd.sign$var.sel, rownames(sign.matrix)), 1] <- 1
sign.matrix[match(meta.sird.sign$var.sel, rownames(sign.matrix)), 2] <- 1
sign.matrix[match(meta.mod.sign$var.sel, rownames(sign.matrix)), 3] <- 1
sign.matrix[match(meta.mard.sign$var.sel, rownames(sign.matrix)), 4] <- 1
sign.matrix[match(meta.mardh.sign$var.sel, rownames(sign.matrix)), 5] <- 1

estimates <- data.frame(
          SIDD = meta.sidd[match(vars, meta.sidd$var),"Effect.random"],
          SIRD = meta.sird[match(vars, meta.sird$var),"Effect.random"],
          MOD = meta.mod[match(vars, meta.mod$var),"Effect.random"],
          MARD = meta.mard[match(vars, meta.mard$var),"Effect.random"],
          MARDH = meta.mardh[match(vars, meta.mardh$var),"Effect.random"])

rownames(estimates) <- vars

# Estimates are inverted 
estimates <- estimates*-1

# Functions for correlation
hclust2 <- function(x, method="average", ...)
	hclust(x, method=method, ...)
dist2 <- function(x, ...)
	as.dist(1-cor(t(x)))

aheatmap(estimates, hclustfun = hclust2, distfun =dist2,
         Colv=NA, breaks = seq(-0.9,.9,length.out = 51), annRow = sign.matrix, 
         annColors = c("#4DB3E6","#00B399","#E69900","#CC80B3","#8B1A4F"), 
         color = colorRampPalette(colors =  c("#030189","white","#FD0000"))(50))

pdf("./003.Figures.combined/Peptidomics heatmap of meta estimates.pdf")
aheatmap(estimates, hclustfun = hclust2, distfun =dist2,
         Colv=NA, breaks = seq(-0.9,.9,length.out = 51), annRow = sign.matrix, 
         annColors = c("#4DB3E6","#00B399","#E69900","#CC80B3","#8B1A4F"), 
         color = colorRampPalette(colors =  c("#030189","white","#FD0000"))(50))

dev.off()
```


## Circos test

```{r, eval=F}
lbs <- labels(as.dendrogram(hclust(dist(estimates))))

#lipids.classes <- read.table("002.Data/SwissLipids.csv", sep=",", header=T)
#lipids.classes <- lipids.classes[lipids.classes$FDBName %in% meta.mard$var.sel,]

#Order
meta.sidd.o <- meta.sidd[match(lbs,meta.sidd$var.sel),]
meta.sird.o <- meta.sird[match(lbs,meta.sird$var.sel),]
meta.mod.o <- meta.mod[match(lbs,meta.mod$var.sel),]
meta.mard.o <- meta.mard[match(lbs,meta.mard$var.sel),]
meta.mardh.o <- meta.mardh[match(lbs,meta.mardh$var.sel),]

#New df
pd <- data.frame(
            seg.name = "Lipidomics",
            seg.Start = seq(1,855, by=3),
            seg.End = seq(3,855, by=3),
            Name = meta.sidd.o$Target,
            Description =  meta.sidd.o$Target)

segv <- data.frame(
            seg.name = "Lipidomics",
            seg.po = seq(2,855, by=3),
            Gene =  meta.sidd.o$Target,
            SIDD = meta.sidd.o$Effect.random * -1,
            SIRD = meta.sird.o$Effect.random * -1,
            MOD = meta.mod.o$Effect.random * -1,
            MARD = meta.mard.o$Effect.random * -1,
            MARDH = meta.mardh.o$Effect.rando * -1
)

head(pd)

library(OmicCircos)
options(stringsAsFactors = F)
source("Z:/Roderick/OmicCircos.R")

# load the OmicCircos-package
db<-segAnglePo(pd,seg=unique(pd$seg.name));

list.in <- table(pd$seg.name)
list.in <- list.in[db[,1]]
getDegree <- function(i, list.in){
  if(i==1 )
  {
   start <- 1 
  }else{
   start <- cumsum(list.in)[i-1]*1.2415614+(i-1)*2
  }
  end <- cumsum(list.in)[i]*1.2415614+(i-1)*2
  data.frame(name = names(list.in)[i], i, start, end)
}

degrees <- getDegree(i = 1, list.in =  list.in)
degrees <- degrees[match(db[,1],degrees$name),]
db[,2] <- degrees$start + 270
db[,3] <- degrees$end + 260

pdf("000.Final_Scripts/002.Clusters.Data/Heatmap plot peptides.pdf", width=7, height=6.75)
par(mar=c(2,2,2,2));
plot(c(1,800),c(1,800),type="n",axes=FALSE,xlab="",ylab="",main="");
circos2(R=400,type="chr",cir=db,print.chr.lab=TRUE,W=4,scale=FALSE,col=viridis::viridis_pal()(9));
circos2(R=250,cir=db,W=150,mapping=segv,col.v=4,type="heatmap2",lwd=1, B=F, col.bar=T, col.bar.po="bottomright", col=viridis::viridis_pal()(4))
circos2(R=410,cir=db,W=20,mapping=segv,type="label",side="out",cex=0.4, col="black")
dev.off()

par(mar=c(2,2,2,2));
plot(c(1,800),c(1,800),type="n",axes=FALSE,xlab="",ylab="",main="");
circos2(R=400,type="chr",cir=db,print.chr.lab=TRUE,W=4,scale=FALSE,col=viridis::viridis_pal()(9));
circos2(R=250,cir=db,W=150,mapping=segv,col.v=4,type="heatmap2",lwd=1, B=F, col.bar=T, col.bar.po="bottomright", col=viridis::viridis_pal()(4))
circos2(R=410,cir=db,W=20,mapping=segv,type="label",side="out",cex=0.4, col="black")
```

```{r, eval=F}
head(conversion)
conversion2 <- conversion[match(pd$Description, conversion$Target),]
head(conversion2)
SIRD.up <- conversion2[which(conversion2$Target == "TGF-b R III"):which(conversion2$Target == "ApoM"),"UniProt"]
MARDH.up <- conversion2[which(conversion2$Target == "NG36"):which(conversion2$Target == "Macrophage scavenger receptor"),"UniProt"]
SIRD.down <- conversion2[which(conversion2$Target == "LPPL"):which(conversion2$Target == "TSP2"),"UniProt"]
MOD.up <- conversion2[which(conversion2$Target == "Leptin"):which(conversion2$Target == "Esterase D"),"UniProt"]


write.table(conversion$UniProt, file="000.Final_Scripts/002.Clusters.Data/All.txt", row.names=F, col.names=F, quote=F)
write.table(SIRD.up, file="000.Final_Scripts/002.Clusters.Data/Peptides_cluster_SIRD_up1.txt", row.names=F, col.names=F, quote=F)
write.table(MARDH.up, file="000.Final_Scripts/002.Clusters.Data/Peptides_cluster_MARDH_up1.txt", row.names=F, col.names=F, quote=F)
write.table(SIRD.down, file="000.Final_Scripts/002.Clusters.Data/Peptides_cluster_SIRD.down1.txt", row.names=F, col.names=F, quote=F)
write.table(MOD.up, file="000.Final_Scripts/002.Clusters.Data/Peptides_cluster_MOD.up1.txt", row.names=F, col.names=F, quote=F)


```




```{r, eval=FALSE, echo=F}
datashield.logout(opal1)
datashield.logout(opal2)
```